name: Build and deploy to Azure

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Start CosmosDB Emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1

    - name: Run tests
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        COSMOSDB_ENDPOINT: https://localhost:8081
        COSMOSDB_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        COSMOSDB_DB_ID: spotify
        COSMOSDB_CONTAINER_ID: users
        FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        FUNCTION_KEY: ${{ secrets.FUNCTION_KEY }}
      run: npm run test

    - name: Build project
      run: npm run build
      
    - name: Deploy to Azure function
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
