name: Build, test and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-latest
    name: Build and test
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: npm
      
    - run: npm install --production=false

    - run: npm run build
      
    - name: Setup CosmosDB emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1

    - run: npm test
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        COSMOSDB_ENDPOINT: https://localhost:8081
        COSMOSDB_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        COSMOSDB_DB_ID: spotify
        COSMOSDB_CONTAINER_ID: users
        FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        FUNCTION_KEY: ${{ secrets.FUNCTION_KEY }}

    - name: Remove dev dependencies
      run: npm prune --production

    - run: mv node_modules dist/node_modules
      
    - name: Archive dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          host.json
          package.json
    
    - name: Archive coverage summary
      uses: actions/upload-artifact@v3
      with:
        name: coverage-summary
        path: coverage/coverage-summary.json
    
  deploy:
    needs: build_and_test
    runs-on: windows-latest
    name: Deploy to Azure  
    steps:
    - uses: actions/download-artifact@v3
      
    - name: Parse coverage data
      run: echo "PERCENT=$((Get-Content coverage-summary\coverage-summary.json | Out-String | ConvertFrom-Json).total.lines.pct)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Update coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.BADGE_TOKEN }}
        gistID: 342ee9e95e5604afaa2ee223f30f4dbd
        filename: coverage.json
        label: coverage
        message: ${{ format('{0}%', env.PERCENT) }}
        color: success
        isError: ${{ env.PERCENT < 70 }}
        namedLogo: jest
        logoColor: white
      
    - name: Deploy to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: dist
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
